### ISSUE TITLE
界面启动了，摄像头语音能打开但是点击开始对话的时候一直等待，证书已经配了，然后终端出现了 ERROR    | chat_engine.contexts.handler_context:submit_data:24 - Session is not started, data submitter not ready.

### ISSUE THREAD

**Issue by zpylyuuuu** [HumanAIGC-Engineering/OpenAvatarChat#52]
2025-04-24 21:46:21.433 | ERROR    | chat_engine.contexts.handler_context:submit_data:24 - Session is not started, data submitter not ready.

**Comment by zpylyuuuu** [comment]
![Image](https://github.com/user-attachments/assets/93879300-ef9d-49d9-af62-b2f8239c005f)

**Comment by wzr0108** [comment]
是在远程服务器运行吗

**Comment by zpylyuuuu** [comment]
> 是在远程服务器运行吗

对的，阿里服务器上部署，远程访问，在本地打开，host配置文件是0.0.0.0 和121.0.0.1都试过，都是这个情况

**Comment by wzr0108** [comment]
我的服务器和pc在同一个网络，也是不行

**Comment by zpylyuuuu** [comment]
> 我的服务器和pc在同一个网络，也是不行

是同一个报错吗，我用API版和本地minio2.6都不行

**Comment by wzr0108** [comment]
我没有这个报错，但也是启动不了，浏览器一直等待中，控制台显示chat session stopped

**Comment by wzr0108** [comment]
你的远程部署还做了什么操作吗

**Comment by zpylyuuuu** [comment]
没有，就是按着步骤来
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Zhaorun ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2025年4月25日 16:32
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [HumanAIGC-Engineering/OpenAvatarChat] 界面启动了，摄像头语音能打开但是点击开始对话的时候一直等待，证书已经配了，然后终端出现了 ERROR    | chat_engine.contexts.handler_context:submit_data:24 - Session is not started, data submitter not ready. (Issue #52)
        
      
    
  
wzr0108 left a comment (HumanAIGC-Engineering/OpenAvatarChat#52)
你的远程部署还做了什么操作吗

**Comment by wzr0108** [comment]
执行了scripts/setup_coturn.sh，配置文件是这样填吗
```
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
    rtc_config:
      # 使用turnserver时，使用以下配置
      urls: ["turn:turn.116-136-52-78.turnserver:3478", "turns:turn.116-136-52-78.turnserver:5349"]
      username: "username"
      credential: "password"
```
